final List<Map<String, String>> tableData = [
  {
    'no': '1',
    'subject': 'S01001',
    'status': 'Screening',
    'sync status': 'Partially Done',
    'sex': '남',
    'age': '-',
  },
  {
    'no': '2',
    'subject': 'S01002',
    'status': 'Screening',
    'sync status': 'Partially Done',
    'sex': '남',
    'age': '-',
  },
  {
    'no': '3',
    'subject': 'S01003',
    'status': 'Complete',
    'sync status': 'Partially Done',
    'sex': '남',
    'age': '-',
  },
  {
    'no': '4',
    'subject': 'S01004',
    'status': 'Drop out',
    'sync status': 'Partially Done',
    'sex': '여',
    'age': '-',
  },
  {
    'no': '5',
    'subject': 'S01005',
    'status': 'Screening',
    'sync status': 'Partially Done',
    'sex': '남',
    'age': '-',
  },
  {
    'no': '6',
    'subject': 'S01006',
    'status': 'Screening Fail',
    'sync status': 'Partially Done',
    'sex': '남',
    'age': '-',
  },
];
